### ISSUE TITLE
[IDEA] Add a license

### ISSUE THREAD

**Issue by Panquesito7** [LearnWithCommunity/learnwith.community#1]
**Description**

We should add a license to this repository. This way, people will know what and what not they can do with this repository, permissions, notices, etc.. I suggest adding the [**MIT license**](https://mit-license.org).

**Additional Context**

https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/

**Comment by vsnthdev** [comment]
Even though the source is open, we're thinking of using a restricted license.

Not an open-source license.

**Comment by Panquesito7** [comment]
> Even though the source is open, we're thinking of using a restricted license.
> 
> Not an open-source license.

Should we use AGPLv3.0+, then?

**Comment by vsnthdev** [comment]
We'll probably write a custom license for this project.
